/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : UnRTF
 #	author : miyako
 #	2018/11/26
 #
 # --------------------------------------------------------------------------------*/

#ifndef __4DPLUGIN_H__
#define __4DPLUGIN_H__ 1

#include "config.h"

#ifdef HAVE_STDIO_H
#include <stdio.h>
#endif

#ifdef HAVE_STDLIB_H
#include <stdlib.h>
#endif

#ifdef HAVE_STRING_H
#include <string.h>
#endif

#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif

#include "defs.h"
#include "error.h"
#include "word.h"
#include "convert.h"
#include "parse.h"
#include "hash.h"
#include "malloc.h"
#include "path.h"
#include "output.h"
#include "user.h"
#include "util.h"
#include "main.h"

#define THIS_BUNDLE_ID @"com.4D.UnRTF"
#define THIS_BUNDLE_NAME L"UnRTF.4DX"

// --- UnRTF
void UnRTF(sLONG_PTR *pResult, PackagePtr pParams);

typedef enum
{
    UnRTF_Output_HTML = 0,
    UnRTF_Output_plain_text = 1,
    UnRTF_Output_VT100 = 2,
    UnRTF_Output_LaTeX =  3
} UnRTF_Output;

void user_init(UnRTF_Output format);

#endif
